name: paintshop_snakemake
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.77
  - gffread=0.12.1
  - pandas=1.1.0
  - pip=20.1.1
  - python=3.8.3
  - snakemake=5.20.1
  